### ISSUE TITLE
use more human readable for units

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_explorer_ui#11]
![image](https://user-images.githubusercontent.com/64129/130027873-d3016ac2-6002-4f1d-86f6-1ed30802ff2d.png)

values of uptime, mru, cru, .. etc aren't human readable

**Comment by MohamedElmdary** [comment]
Added units to values:
cru => CPU
src/hru/mru => TB or GB depends of the amount of bytes
uptime => shows the most two highest units .
Example:
```ts
const uptime0  = 365 * 24 * 3600; 
secondToRedable(uptime0); // 1 Year

const uptime1 = 365 * 24 * 3600 +  5; // 5 seconds
secondToRedable(uptime1); // 1 Year, 5 Seconds

const uptime2 = 365 * 24 * 3600 +  10 * 24 * 60 * 60  + 5 seconds; //  10 days + 5 seconds
secondToRedable(uptime2); // 1 Year, 10 Days (note ignore seconds)

const uptime3 = 365 * 24 * 3600 + ...; //  5 months +  10 days + 5 seconds
secondToRedable(uptime3); // 1 Year, 5 Months  (note ignore days/seconds)
```

if value is not given returns  => Unknown
if value is equal to `0` returns  => None

![image](https://user-images.githubusercontent.com/31689104/130063420-a685e0c9-2c6f-4dec-a6af-238c1b2cf7d4.png)
![image](https://user-images.githubusercontent.com/31689104/130063477-de0756dd-c2f2-4539-88a8-03aafbdde6e3.png)
