### ISSUE TITLE
Nodes have inconsistant data.

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_explorer_ui#4]
Some nodes have a cityId which doesn't exist in gql.

Following query shows the issue
```gql
{
  nodes {
    cityId
  }
  
  cities(
    where: {
      id_eq: 0 # all nodes returns same id :(
    }
  ) {
    id
  }
}
```

**Comment by DylanVerstraete** [comment]
Node's City/Country data is not passed correctly at this time of writing. It's just dummy data, we pass country_id:0 and city_id: 0.

Don't worry about it for now
