### ISSUE TITLE
make the most used filters standout

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_explorer_ui#6]

**Comment by MohamedElmdary** [comment]
Add a new way to show some filter by default
![image](https://user-images.githubusercontent.com/31689104/130054516-938acda2-70b7-4cc7-84e9-3810b0ba9c39.png)

**Comment by MohamedElmdary** [comment]
Add a new way to show some filter by default
![image](https://user-images.githubusercontent.com/31689104/130054615-8e6fe7f0-69bf-49e8-8885-080a71655864.png)
