### ISSUE TITLE
add Dockerfile

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_explorer_ui#9]

**Comment by MohamedElmdary** [comment]
Added *Dockerfile* with 2 stages
1- using `node:12.2.0-alpine` to build vue app
2- using `nginx:1.16.0-alpine` with custom conf to serve `dist` folder

![image](https://user-images.githubusercontent.com/31689104/130078853-415e7e21-a324-43c4-9871-3a3af0d9715a.png)
